"""driver_name

Revision ID: 7d5a27729bcb
Revises: 31f2e01bfc6e
Create Date: 2022-08-03 18:02:00.920540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5a27729bcb'
down_revision = '31f2e01bfc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('name', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'name')
    # ### end Alembic commands ###
